import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Sidebar from './components/sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex gap-2'>

        <div className='my-12 p-2'>
          <Sidebar />
        </div>
        <div className='w-full my-14 mx-4 rounded-lg bg-slate-300 p-2'>
        {children}
        </div>
        </div>
        
        </body>
    </html>
  )
}
